### ISSUE TITLE
Getting an ClassNotFound exception when using version 1.8.1 of avro

### ISSUE THREAD

**Issue by hmmlopez** [phunt/avro-rpc-quickstart#13]
Hello I'm getting an error after downloading and executing:

 **mvn clean generate-sources**

`[ERROR] Failed to execute goal org.apache.avro:avro-maven-plugin:1.8.1:protocol (schemas) on project avro-rpc-quickstart: Execution schemas of goal org.apache.avro:avro-maven-plugin:1.8.1:protocol failed: A required class was missing while executing org.apache.avro:avro-maven-plugin:1.8.1:protocol: org/codehaus/jackson/node/TextNode
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.avro:avro-maven-plugin:1.8.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy`

here

`Caused by: java.lang.ClassNotFoundException: org.codehaus.jackson.node.TextNode
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 26 more`

I'm new to Avro and was looking for an example that works with version 1.8.1, so I found this project but also checking this code out I'm receiving the same error.
I tried first the explination on the official avro page where I received the same error while having everything configured as they mentioned.

I do see the **jackson-mapper-asl-1.9.13.jar** containing the missing class on my classpath (org.codehaus.jackson.node.TextNode.class) added by maven so I'm not sure why it is not working.

The only version that is working without error for me is Avro version 1.7.5. Newer versions than that are giving me the error mentioned above. Any tips or hint would be helpfull.

I'm running it under
OS: Ubuntu 16.04 LTS, 
Java: JDK 1.8.0_121
IDE: Neon.2 Release (4.6.2)
maven: 3.3.9

**Comment by hmmlopez** [comment]
I managed to fix it by deleting everything in my local maven repository under org/codehaus/jackson. 
Probably the file got corrupted when downloading from internet. 
I'm trying to close the issue, cause it's irrelevant to the project.
