### ISSUE TITLE
Interoperability between Java and Ruby doesn't exist

### ISSUE THREAD

**Issue by fltiago** [phunt/avro-rpc-quickstart#9]
I'm trying to build a Java server with a Ruby client and for some reason doesn't work, apparently there is a error comparing types between Java and Ruby which raise the following exception:

```
java.lang.IllegalArgumentException: Illegal Capacity: -1985359361
	at java.util.ArrayList.<init>(ArrayList.java:156)
	at org.apache.avro.ipc.NettyTransportCodec$NettyFrameDecoder.decodePackHeader(NettyTransportCodec.java:172)
	at org.apache.avro.ipc.NettyTransportCodec$NettyFrameDecoder.decode(NettyTransportCodec.java:139)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:286)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:208)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:94)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:364)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:238)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Any idea how to fix this?

**Comment by fltiago** [comment]
I found at Avro user mailing list that is a known problem: http://mail-archives.apache.org/mod_mbox/avro-user/201306.mbox/%3CCAOTir42R9OpURWqrpx5+7aUK7awOzCFWJjsWSE2ez0-qhjP6Ug@mail.gmail.com%3E

Seems that the implementation between the transport is different in Java and Ruby, which cause a interop problem.

@phunt Do you already test a java server with a ruby/python client?

**Comment by phunt** [comment]
I didn't realize that, thanks for the report. I do not have such a server iirc.

**Comment by shenberg** [comment]
Use an HTTP server for java and interop will work. There's no netty client or server for python either.
